{
 "title": "Nearform Alerts",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  { "title": "Alert List", "type": "alertlist", "gridPos": { "h": 22, "w": 7, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage by pod",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"bitswap-peer\", pod=~\"bitswap-peer.*\"}[1m])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage %  by pod",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 17, "x": 7, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * max by (pod)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"bitswap-peer\", container!=\"\", image!=\"\"}) / on (pod) max by (pod)(kube_pod_container_resource_limits{namespace=\"bitswap-peer\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "Open FDs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "process_open_fds{job=~\".*_ipfscluster\"}"
    }
   ]
  },
  {
   "title": "Messages on Indexer DLQ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "dimensions": { "QueueName": "indexer-topic-dlq" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Messages on Indexer DLQ - P1 Alert",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "dimensions": { "QueueName": "indexer-topic-dlq" },
     "metricName": "NumberOfMessagesReceived",
     "namespace": "AWS/SQS",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "Indexer Errors, Invocations and Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
   "targets": [
    {
     "dimensions": { "FunctionName": "indexer" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FunctionName": "indexer" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    { "expression": "100 - 100 * $A / $B", "type": "math" }
   ]
  },
  {
   "title": "bucket-to-indexer errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 8, "y": 38 },
   "targets": [
    {
     "dimensions": { "FunctionName": "bucket-to-indexer" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FunctionName": "bucket-to-indexer" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    { "expression": "100 - 100 * $A / $B", "type": "math" }
   ]
  },
  {
   "title": "side-indexer errors",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 38 },
   "targets": [
    {
     "dimensions": { "FunctionName": "side-indexer" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "FunctionName": "side-indexer" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    { "expression": "100 - 100 * $A / $B", "type": "math" }
   ]
  },
  {
   "title": "Advertisement Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expression": "filter @message like \"Announcing to the indexer node failed\"\n| stats count(*) as `Announcing to the indexer node failed` by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "log",
     "queryMode": "Logs",
     "region": "default",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Daily Charges AWS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expression": "IF(m2>0, m2)",
     "id": "m3",
     "label": "Total estimated daily charge",
     "metricEditorMode": 1,
     "period": "86400",
     "queryMode": "Metrics",
     "region": "us-east-1",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Peer: bafzbeibhqavlasjc7dvbiopygwncnrtvjd2xmryk5laib7zyjor6kf3avm",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(nftcheckup_connection_errors_total{peer=\"bafzbeibhqavlasjc7dvbiopygwncnrtvjd2xmryk5laib7zyjor6kf3avm\"}[1h]) / ignoring(responded,found) rate(nftcheckup_samples_total[1h])",
     "legendFormat": "Connection Errors"
    },
    {
     "expr": "rate(nftcheckup_bitswap_requests_total{responded=\"true\",found=\"true\", peer=\"bafzbeibhqavlasjc7dvbiopygwncnrtvjd2xmryk5laib7zyjor6kf3avm\"}[1h]) / ignoring(responded,found) rate(nftcheckup_samples_total[1h])",
     "legendFormat": "Found"
    }
   ]
  },
  {
   "title": "Goroutines Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "max(go_goroutines{job=~\".*[nft|web]*._ipfscluster\"})"
    }
   ]
  },
  {
   "title": "Memory Usage %  by pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "100 * max by (pod)(container_memory_working_set_bytes{job=\"kubelet\", metrics_path=\"/metrics/cadvisor\", namespace=\"bitswap-peer\", container!=\"\", image!=\"\"}) / on (pod) max by (pod)(kube_pod_container_resource_limits{namespace=\"bitswap-peer\", resource=\"memory\"})"
    }
   ]
  },
  {
   "title": "CPU Usage by pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{namespace=\"bitswap-peer\", pod=~\"bitswap-peer.*\"}[1m])) by (pod)"
    }
   ]
  }
 ]
}