{
 "title": "DynamoDB",
 "time": { "from": "2022-11-14T03:00:00.000Z", "to": "2022-11-20T02:59:59.000Z" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "tableName",
    "label": "TableName",
    "query": "cars, blocks, prod-ep-v1-blocks-cars-position, prod-ep-v1-cars, prod-ep-v1-blocks"
   }
  ]
 },
 "panels": [
  { "title": "Account Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Scan: Successful Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "Scan", "TableName": "$tableName" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "GetItem: Successfull Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "GetItem", "TableName": "$tableName" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Table Metrics: Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Scan: Successful Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "Scan", "TableName": "$tableName" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "DeleteItem: Successfull Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "DeleteItem", "TableName": "$tableName" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "PutItem: Successfull Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "PutItem", "TableName": "$tableName" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "BatchWriteItem: Successfull Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "BatchWriteItem", "TableName": "$tableName" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "UpdateItem: Successfull Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "UpdateItem", "TableName": "$tableName" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Query: Successfull Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "dimensions": { "Operation": "Query", "TableName": "$tableName" },
     "metricName": "SuccessfulRequestLatency",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Table Metrics: Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Item: SystemErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Operation": "PutItem", "TableName": "$tableName" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "GetItem", "TableName": "$tableName" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "DeleteItem", "TableName": "$tableName" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "BatchWriteItem", "TableName": "$tableName" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "UpdateItem", "TableName": "$tableName" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Query: SystemErrors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "Operation": "Query", "TableName": "$tableName" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "Scan", "TableName": "$tableName" },
     "metricName": "SystemErrors",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Capacity Units", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Consumed Read Capacity Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
   "targets": [
    {
     "dimensions": { "TableName": "$tableName" },
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Provisioned Read Capacity Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
   "targets": [
    {
     "dimensions": { "TableName": "$tableName" },
     "metricName": "ProvisionedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Consumed Write Capacity Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
   "targets": [
    {
     "dimensions": { "TableName": "$tableName" },
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Provisioned Write Capacity Units",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
   "targets": [
    {
     "dimensions": { "TableName": "$tableName" },
     "metricName": "ProvisionedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  { "title": "Operation Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Throttled Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "dimensions": { "Operation": "BatchWriteItem" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "GetItem" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "UpdateItem" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "PutItem" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "Scan" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "DeleteItem" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "Query" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "Operation": "Scan" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "TableName": "$tableName" },
     "metricName": "WriteThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "TableName": "$tableName" },
     "metricName": "ThrottledRequests",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "TableName": "$tableName" },
     "metricName": "ThrottledPutRecordCount",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "TableName": "$tableName" },
     "metricName": "ReadThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "TableName": "$tableName" },
     "metricName": "OnlineIndexThrottleEvents",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Returned Item Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "metricName": "ReturnedItemCount",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DDB Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "TableName": "$tableName" },
     "id": "read",
     "metricName": "ConsumedReadCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "$tableName" },
     "id": "write",
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "$tableName" },
     "expression": "write / PERIOD(write)",
     "id": "writeconsumed",
     "label": "Write Units",
     "metricEditorMode": 1,
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "TableName": "$tableName" },
     "expression": "read / PERIOD(read)",
     "id": "readconsumed",
     "label": "Read Units",
     "metricEditorMode": 1,
     "metricName": "ConsumedWriteCapacityUnits",
     "namespace": "AWS/DynamoDB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  }
 ]
}