{
 "title": "AWS Lambda",
 "description": "Visualize AWS Lambda metrics",
 "tags": [
  "monitoringartist",
  "cloudwatch"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "functionname",
    "label": "FunctionName",
    "query": "dimension_values($region,AWS/Lambda,Duration,FunctionName)"
   }
  ]
 },
 "panels": [
  { "title": "Bitswap peer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Execution Errors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dimensions": { "FunctionName": "$functionname" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "label": "${PROP('MetricName')} ${PROP('Stat')}",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Throttles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Dead Letter Error",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Global Concurrent Executions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "UnreservedConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 43 },
   "options": {
    "content": "<a style=\"float: right\" href=\"http://www.monitoringartist.com\" target=\"_blank\" title=\"Dashboard maintained by Monitoring Artist - DevOps / Docker / Kubernetes / AWS ECS / Google GCP / Zabbix / Zenoss / Terraform / Monitoring\"><img src=\"https://monitoringartist.github.io/monitoring-artist-logo-grafana.png\" height=\"30px\" /></a>\n<a style=\"float: left\"  target=\"_blank\" href=\"http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/lam-metricscollected.html\">AWS CloudWatch Lambda documentation</a><br/>\n<a style=\"float: left\"  target=\"_blank\" href=\"https://grafana.net/dashboards/593\">Installed from Grafana.net dashboards</a>\n<div style=\"clear:both; width:100%;height:0;font-size:0;\"></div>"
   },
   "targets": [
    {}
   ]
  },
  { "title": "Lambda - Indexer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Indexing CAR complete (duration)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expression": "filter msg = \"Indexing CAR complete\" \n | stats avg(duration) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Indexing CAR complete (ContentLength)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter msg = \"Indexing CAR complete\" \n | stats avg(source.contentLength) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Indexing CAR complete (Blocks)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter msg = \"Indexing CAR complete\" \n | stats avg(blocks) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Dynamo metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats avg(`metrics.dynamo-batch-inserts-durations.mean`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats avg(`metrics.dynamo-creates-durations.mean`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Dynamo metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 61 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats sum(`metrics.dynamo-batch-inserts-count`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats sum(`metrics.dynamo-creates-count`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats sum(`metrics.dynamo-creates-count`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats sum(`metrics.dynamo-creates-durations.sum`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "S3 metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats avg(`metrics.s3-fetchs-durations.mean`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "S3 metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats sum(`metrics.s3-fetchs-durations.count`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "SQS metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats avg(`metrics.sqs-publishes-batch-durations.mean`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats avg(`metrics.sqs-publishes-durations.mean`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "SQS metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats sum(`metrics.sqs-publishes-batch-durations.count`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter ipfs_provider_component = \"indexer-lambda\" \n | stats sum(`metrics.sqs-publishes-durations.count`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter msg = \"Cannot index the CAR file\"\n| stats count(*) as `Cannot index the CAR file` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter msg = \"Cannot write batch items to DynamoDB table\"\n| stats count(*) as `Cannot write batch items to DynamoDB table` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter msg = \"Error writing blocks\"\n| stats count(*) as `Error writing blocks` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter msg = \"Cannot send command to DynamoDB after 3 attempts\"\n| stats count(*) as `Cannot send command to DynamoDB after 3 attempts` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter msg = \"Error queuing block tasks\"\n| stats count(*) as `Error queuing block tasks` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter msg = \"Cannot insert item into DynamoDB\"\n| stats count(*) as `Cannot insert item into DynamoDB` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter msg = \"Cannot update item in DynamoDB table cars\"\n| stats count(*) as `Cannot update item in DynamoDB table cars` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter msg = \"Cannot insert item into DynamoDB table blocks\"\n| stats count(*) as `Cannot insert item into DynamoDB table blocks` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter msg like \"Cannot open file S3 URL s3:\"\n| stats count(*) as `Cannot open file S3 URL s3:` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Errors Logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "fields @message\n| filter @type != \"END\" and @type != \"START\" and @type != \"REPORT\" and msg != \"Dumping metrics ...\"\nand ipfs_provider_component != \"indexer-lambda\"\nand (@message like \"ERROR\" or @message like \"error\" or @message like \"Error\") and @message not like \"Indexing CAR complete\" and @message not like \"sent sns message on topic\"",
     "logGroupNames": [ "/aws/lambda/indexer" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region"
    }
   ]
  },
  {
   "title": "Lambda - Publishing Advertisement",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 }
  },
  {
   "title": "HTTP metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"publisher-advertisement-lambda\" \n | stats avg(`metrics.http-indexer-announcements-durations.mean`) by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter ipfs_provider_component = \"publisher-advertisement-lambda\" \n | stats avg(`metrics.http-head-cid-fetchs-durations.mean`) by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "HTTP metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"publisher-advertisement-lambda\"\n | stats sum(`metrics.http-indexer-announcements-durations.count`) by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter ipfs_provider_component = \"publisher-advertisement-lambda\"\n | stats sum(`metrics.http-head-cid-fetchs-durations.count`) by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "S3 metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"publisher-advertisement-lambda\" \n | stats avg(`metrics.s3-uploads-durations.mean`) by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter ipfs_provider_component = \"publisher-advertisement-lambda\" \n | stats avg(`metrics.s3-fetchs-durations.mean`) by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "S3 metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"publisher-advertisement-lambda\"\n | stats sum(`metrics.s3-uploads-durations.count`) by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter ipfs_provider_component = \"publisher-advertisement-lambda\"\n | stats sum(`metrics.s3-fetchs-durations.count`) by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "General metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter msg = \"notifyIndexer at https://cid.contact/ingest/announce\"\n| stats count(*) as `notifyIndexer at https://cid.contact/ingest/announce` by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter msg = \"Downloading PeerId from s3://ipfs-peer-bitswap-config/peerId.json\"\n| stats count(*) as `Downloading PeerId from s3://ipfs-peer-bitswap-config/peerId.json` by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Errors Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 123 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "fields @message\n| filter @type != \"END\" and @type != \"START\" and @type != \"REPORT\"\nand ipfs_provider_component != \"publisher-advertisement-lambda\"\nand (@message like \"ERROR\" or @message like \"error\" or @message like \"Error\" or @message like \"failed\" or @message like \"Failed\")\n",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter @type != \"END\" and @type != \"START\" and @type != \"REPORT\"\nand ipfs_provider_component != \"publisher-advertisement-lambda\"\nand (@message like \"ERROR\" or @message like \"error\" or @message like \"Error\" or @message like \"Failed\"  or @message like \"failed\") and @message not like \"Announcing to the indexer node failed\"\n| stats count(*) as `Other errors` by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "filter @message like \"Announcing to the indexer node failed\"\n| stats count(*) as `Announcing to the indexer node failed` by bin(1m)",
     "logGroupNames": [
      "/aws/lambda/publishing-advertisement"
     ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  { "title": "Lambda - Publishing Content", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 144 } },
  {
   "title": "S3 metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"publisher-content-lambda\" \n | stats avg(`metrics.s3-uploads-durations.mean`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/publishing-content" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "S3 metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 145 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"publisher-content-lambda\"\n | stats sum(`metrics.s3-uploads-durations.count`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/publishing-content" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "SQS metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"publisher-content-lambda\" \n | stats avg(`metrics.sqs-publishes-durations.mean`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/publishing-content" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "SQS metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 155 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "filter ipfs_provider_component = \"publisher-content-lambda\"\n | stats sum(`metrics.sqs-publishes-durations.count`) by bin(1m)",
     "logGroupNames": [ "/aws/lambda/publishing-content" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "General metrics",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expression": "stats sum(records) as `Published records` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/publishing-content" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    },
    {
     "expression": "stats sum(elapsed) as `Elapsed` by bin(1m)",
     "logGroupNames": [ "/aws/lambda/publishing-content" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region",
     "statsGroups": [ "bin(1m)" ]
    }
   ]
  },
  {
   "title": "Errors Logs",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 165 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expression": "fields @message\n| filter @type != \"END\" and @type != \"START\" and @type != \"REPORT\"\nand ipfs_provider_component != \"publisher-content-lambda\"\nand (@message like \"ERROR\" or @message like \"error\" or @message like \"Error\")\n",
     "logGroupNames": [ "/aws/lambda/publishing-content" ],
     "namespace": "AWS/Lambda",
     "queryMode": "Logs",
     "region": "$region"
    }
   ]
  }
 ]
}