{
 "title": "Bitswap Peer",
 "time": { "from": "2022-10-20T08:53:56.903Z", "to": "2022-10-20T09:30:31.034Z" },
 "templating": {
  "list": [
   { "name": "cluster" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=~\".*bitswap-peer\"}, pod)"
    }
   },
   { "name": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bitswap_total_connections_count_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bitswap_active_connections_count{pod=~\"$pod\"} > 0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bitswap_total_entries_count_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Entries",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bitswap_pending_entries_count{pod=~\"$pod\", namespace=\"bitswap-peer\"} > 0) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hits",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bitswap_block_data_hits_count_total{pod=~\"$pod\"}[$__range]))+sum(increase(bitswap_block_info_hits_count_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Misses",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(bitswap_block_info_misses_count_total{pod=~\"$pod\"}[$__range]))+sum(increase(bitswap_block_data_misses_count_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DynamoDB Reads",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(dynamo_request_durations_count{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Fetches",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(s3_request_durations_count{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Data (Bytes)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(bitswap_sent_data_count_total{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=~\".*bitswap-peer\", pod=~\"$pod\", container!=\"\", image!=\"\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{namespace=~\".*bitswap-peer\", pod=~\"$pod\", container=~\".*bitswap-peer\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pods Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*bitswap-peer\", phase=\"Running\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*bitswap-peer\", phase=\"Pending\"})",
     "legendFormat": "Pending"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*bitswap-peer\", phase=\"Failed\"})",
     "legendFormat": "Failed"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*bitswap-peer\", phase=\"Unknown\"})",
     "legendFormat": "Unknown"
    },
    {
     "expr": "sum(kube_pod_status_phase{namespace=~\".*bitswap-peer\", phase=\"Succeeded\"})",
     "legendFormat": "Succeeded"
    }
   ]
  },
  {
   "title": "Containers Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_running{namespace=~\".*bitswap-peer\"})",
     "legendFormat": "Running"
    },
    {
     "expr": "sum(kube_pod_container_status_waiting{namespace=~\".*bitswap-peer\"})",
     "legendFormat": "Waiting"
    },
    {
     "expr": "sum(kube_pod_container_status_terminated{namespace=~\".*bitswap-peer\"})",
     "legendFormat": "Terminated"
    }
   ]
  },
  {
   "title": "Total Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "(kube_pod_container_status_restarts_total{namespace=~\".*bitswap-peer\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Deployment Replicas - Up To Date",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "kube_replicaset_spec_replicas{namespace=~\".*bitswap-peer\"}",
     "legendFormat": "{{ replicaset}}"
    }
   ]
  },
  {
   "title": "ReplicaSet creation",
   "type": "timeseries",
   "description": "https://iamonkar.dev/prometheus-k8s-three/",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(max(kube_replicaset_created {replicaset=~\"bitswap-peer.*\"}) by (replicaset) >=\r\ntimestamp(max(kube_replicaset_created {replicaset=~\"bitswap-peer.*\"}) by (replicaset)) - (($__interval_ms / 1000) * 3)) <= bool\r\ntimestamp(max(kube_replicaset_created {replicaset=~\"bitswap-peer.*\"}) by (replicaset)) + (($__interval_ms / 1000) * 2)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Bitswap", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Pod Restarts",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\".*bitswap-peer\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "targets": [
    {
     "expr": "sum(kube_pod_container_status_restarts_total{namespace=~\".*bitswap-peer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "avg(bitswap_active_connections_count{namespace=~\".*bitswap-peer\"}) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 41 },
   "targets": [
    {
     "expr": "sum(bitswap_active_connections_count{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "expr": "sum(increase(bitswap_total_connections_count_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending Entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "expr": "sum(bitswap_pending_entries_count{pod=~\"$pod\",namespace=~\".*bitswap-peer\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Entries",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum(bitswap_total_entries_count_total{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Misses",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 59 },
   "targets": [
    {
     "expr": "sum(bitswap_block_data_misses_count_total{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(bitswap_block_info_misses_count_total{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Block Hits",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(bitswap_block_data_hits_count_total{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(bitswap_block_info_hits_count_total{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sent Data (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(bitswap_sent_data_count_total{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Hits",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 78 },
   "targets": [
    {
     "expr": "sum(increase(bitswap_block_data_hits_count_total{pod=~\"$pod\"}[$__range]))+sum(increase(bitswap_block_info_hits_count_total{pod=~\"$pod\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "AWS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "S3 Fetches",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(s3_request_durations_bucket{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "S3 Fetch Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(s3_request_durations_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(s3_request_durations_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "min(s3_request_durations_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "stddev (s3_request_durations_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DynamoDB Reads",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(dynamo_request_durations_bucket{pod=~\"$pod\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DynamoDB Reads Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(dynamo_request_durations_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.5 , sum by (job,le)\n  (rate(dynamo_request_durations_bucket{ job=\"bitswap-peer-http\"}[1m]))\n)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max (dynamo_request_durations_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "min (dynamo_request_durations_bucket)",
     "legendFormat": "__auto"
    },
    {
     "expr": "stddev ( dynamo_request_durations_bucket)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Compute Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=~\".*bitswap-peer\", pod=~\"$pod\", container!=\"\", image!=\"\"}) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\".*bitswap-peer\", pod=~\"$pod\", container=~\".*bitswap-peer\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(container_memory_working_set_bytes{cluster=\"$cluster\", namespace=~\".*bitswap-peer\", container!=\"\", image!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage by Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 120 },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{namespace=~\".*bitswap-peer\", pod=~\"$pod\", container=~\".*bitswap-peer\"}[$__range])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}