apiVersion: v2
name: prometheus-dependencies
description: A Helm chart for installing Prometheus stack and Service Monitors
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
- name: kube-prometheus-stack
  repository: "https://prometheus-community.github.io/helm-charts"
  version: "~> 30.0.0"
# - name: prometheus
#   repository: "https://prometheus-community.github.io/helm-charts"
#   version: "~> 15.5.3"
