bitswapPeer:
  repoURL: "https://github.com/elastic-ipfs/bitswap-peer-deployment.git"
  targetRevision: HEAD # Replaced in Terraform
  releaseName: elastic-ipfs-bitswap-peer # Replaced in Terraform
  namespace: default # Replaced in Terraform
  valueFileNames: # Replaced in Terraform
  - "values.yaml"
  values:
fluentd:
  repoURL: "https://github.com/elastic-ipfs/fluentd-containers-deployment.git"
  targetRevision: HEAD
  releaseName: fluentd
  namespace: logging # Replaced in Terraform
  valueFileNames: # Replaced in Terraform
  - "values.yaml"
argo-cd:
  installCRDs: false
  dex:
    enabled: false
