apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
  labels:
    app: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      name: curl
      labels:
        app: curl
        workerType: fargate
    spec:
      containers:
      - name: sleep
        image: curlimages/curl
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
