apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitswap-peer
  namespace: argocd
spec:
  project: default

  source:
    repoURL: {{ .Values.bitswap-peer.repoURL }}
    targetRevision: HEAD
    path: helm
    helm:
      releaseName: {{ .Values.bitswap-peer.releaseName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
