apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitswap-peer
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: test-bot
    notifications.argoproj.io/subscribe.on-deployed.slack: test-bot
    notifications.argoproj.io/subscribe.on-health-degraded.slack: test-bot
    notifications.argoproj.io/subscribe.on-sync-failed.slack: test-bot
    notifications.argoproj.io/subscribe.on-sync-running.slack: test-bot
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: test-bot
spec:
  project: default
  source:
    repoURL: {{ .Values.bitswapPeer.repoURL }}
    targetRevision: HEAD
    path: helm
    helm:
      releaseName: {{ .Values.bitswapPeer.releaseName }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.bitswapPeer.namespace }}

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
