bitswap-peer:
  repoURL: https://github.com/web3-storage/ipfs-elastic-provider-bitswap-peer.git
  releaseName: ipfs-elastic-provider-bitswap-peer

argo-cd:
  installCRDs: false
  dex:
    enabled: false
  # server:
  #   extraArgs:
  #     - --insecure # serve the Web UI over http
  # config:
  #   repositories: |
  #     - type: helm
  #       name: stable
  #       url: https://charts.helm.sh/stable
  #     - type: helm
  #       name: argo-cd
  #       url: https://argoproj.github.io/argo-helm
