apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: busybox
  name: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox
        WorkerType: "fargate"
    spec:
      containers:
      - image: busybox
        name: busybox
        resources: {}
        command:
        - sleep
        - "3600"
status: {}
