{
 "title": "Lambda Indexer",
 "tags": [ "TODO: Durations" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "S3 Fetches ",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "indexer_lambda_metrics_s3_fetchs_count_sum"
    }
   ]
  },
  {
   "title": "DynamoDB Reads",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "indexer_lambda_metrics_dynamo_reads_count_sum"
    }
   ]
  },
  {
   "title": "DynamoDB Creates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "indexer_lambda_metrics_dynamo_creates_count_sum"
    }
   ]
  },
  {
   "title": "DynamoDB Updates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "indexer_lambda_metrics_dynamo_updates_count_sum"
    }
   ]
  },
  {
   "title": "SQS Publishes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "indexer_lambda_metrics_sqs_publishes_count_sum"
    }
   ]
  }
 ]
}