{
 "title": "Lambda Publisher",
 "tags": [
  "Under Construction",
  "Broken"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "S3 Fetches",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "publishing_lambda_metrics_s3_fetchs_count_sum"
    }
   ]
  },
  {
   "title": "S3 Uploads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "publishing_lambda_metrics_s3_uploads_count_sum"
    }
   ]
  },
  {
   "title": "SQS Publishes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "publishing_lambda_metrics_sqs_publishes_count_sum"
    }
   ]
  },
  {
   "title": "HTTP Fetches Head ID",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "publishing_lambda_metrics_http_head_cid_fetchs_count_sum"
    }
   ]
  },
  {
   "title": "HTTP Indexer Announcements",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "publishing_lambda_metrics_http_indexer_announcements_count_sum"
    }
   ]
  }
 ]
}