name: 'DNS Auto Deploy'
on:
  push:
    branches:
    - main 
    paths: 
    - 'terraform/dns/**'
    - 'terraform/modules/dns-route53/**'    
  pull_request:
    paths: 
    - 'terraform/dns/**'
    - 'terraform/modules/dns-route53/**'
    
jobs:
  terraform:
    uses: web3-storage/ipfs-elastic-provider-infrastructure/.github/workflows/terraform-aws-shared-workflow.yaml@main 
    with:
      options: -var-file=dns.tfvars
      aws_region: us-west-2
      environment: production
      working_directory: './terraform/dns'
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
