name: 'Prometheus Auto Deploy'
on:
  push:
    branches:
    - main 
    paths: 
    - 'terraform/observability-aws-prometheus/**'
  pull_request:
    paths: 
    - 'terraform/observability-aws-prometheus/**'
jobs:
  terraform:
    uses: web3-storage/ipfs-elastic-provider-infrastructure/.github/workflows/terraform-aws-shared-workflow.yaml@prometheus-workflow 
    with:
      options: -var profile=default
      aws_region: us-west-2
      environment: production
      working_directory: './terraform/observability-aws-prometheus'
    secrets:
      aws_iam_role_to_assume: ${{ secrets.AWS_IAM_ROLE_TO_ASSUME }}
