name: 'Grafana Auto Deploy'
on:
  push:
    branches:
    - main 
    paths: 
    - 'terraform/observability-grafana/**'
  pull_request:
    paths: 
    - 'terraform/observability-grafana/**'
jobs:
  terraform:
    uses: web3-storage/ipfs-elastic-provider-infrastructure/.github/workflows/terraform-aws-shared-workflow.yaml@main 
    with:
      options: -var profile=default -var grafana_auth=${{ secrets.GRAFANA_APP_KEY }}
      aws_region: us-west-2
      environment: production
      working_directory: './terraform/observability-grafana'
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
