name: 'Prometheus Auto Deploy'
on:
  push:
    branches:
    - main 
    paths: 
    - 'terraform/observability-aws-prometheus/**'
  pull_request:
    paths: 
    - 'terraform/observability-aws-prometheus/**'
jobs:
  terraform:
    with:
      aws_region: us-west-2
      environment: production
      working_directory: './terraform/observability-aws-prometheus'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan ${{ inputs.options }} -var region=${{ inputs.aws_region }} -var account-id=${{ secrets.aws_account_id }}
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' 
      run: terraform apply ${{ inputs.options }} -var region=${{ inputs.aws_region }} -var account-id=${{ secrets.aws_account_id }} -auto-approve
