name: 'Grafana Auto Deploy'
on:
  push:
    branches:
    - main 
    paths: 
    - 'terraform/observability-grafana/**'
  pull_request:
    paths: 
    - 'terraform/observability-grafana/**'
jobs:
  terraform:
    runs-on: ubuntu-20.04
    name: 'Terraform'
    environment: production
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/observability-grafana
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan -var grafana_auth=${{ secrets.GRAFANA_APP_KEY }} -var region=us-west-2
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' 
      run: terraform apply -var grafana_auth=${{ secrets.GRAFANA_APP_KEY }} -var region=us-west-2 -auto-approve
