name: 'PeerSubsystem'

on:
  push:
    branches:
    - app-testing
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    env:
      CONTAINER_IMAGE: "ghcr.io/web3-storage/aws-ipfs-bitswap-peer/app:latest"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      KUBECONFIG: $HOME/.kube/config
      AWS_REGION: us-west-2

    defaults:
      run:
        shell: bash
        working-directory: ./terraform/peer-subsystem

    steps:
    - name: Checkout
      uses: actions/checkout@v2

      # TODO: Try again without this step
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # - name: Test AWS authentication
    #   run: aws s3 ls   

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init

    - name: Terraform Plan
      run: terraform plan -var kubeconfig_output_path=$KUBECONFIG -var container_image=$CONTAINER_IMAGE

    - name: Terraform Apply
      run: terraform apply -var kubeconfig_output_path=$KUBECONFIG -var container_image=$CONTAINER_IMAGE -auto-approve
