name: 'Peer Subsystem Auto Deploy'
on:
  push:
    branches:
    - main
    paths: 
    - 'terraform/peer-subsystem/**'
    - 'terraform/modules/eks-auth-sync/**'
    - 'terraform/modules/kube-base-components/**'
  pull_request:
    paths: 
    - 'terraform/peer-subsystem/**'
    - 'terraform/modules/eks-auth-sync/**'
    - 'terraform/modules/kube-base-components/**'
jobs:
  terraform:
    uses: web3-storage/AWS-IPFS-Infrastructure/.github/workflows/terraform-aws-shared-workflow.yaml@main
    with:
      aws_region: us-west-2
      environment: production
      working_directory: './terraform/peer-subsystem'
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
