name: 'Peer Subsystem Manual Deploy'
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version to deploy'
        required: true
        default: 'latest'
jobs:
  terraform:
   # TODO: I seems that complete value has worked. Try to change the beginning with a predefined variable
    uses: ${{ env.GITHUB_REPOSITORY }}/.github/workflows/terraform-aws-shared-workflow.yaml@app-testing
    # uses: web3-storage/AWS-IPFS-Infrastructure/.github/workflows/terraform-aws-shared-workflow.yaml@app-testing
    # uses: ./.github/workflows/terraform-aws-shared-workflow.yaml@app-testing
    with:
      options: -var kubeconfig_output_path=$HOME/.kube/config -var container_image=ghcr.io/web3-storage/aws-ipfs-bitswap-peer/app:latest
      aws_region: us-west-2
    secrets:
      aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
