name: 'Peer Subsystem Manual Deploy'
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version to deploy'
        required: true
        default: 'latest'
jobs:
  terraform:
    uses: ./terraform-aws-shared-workflow.yaml
    options: | 
      -var kubeconfig_output_path=$HOME/.kube/config 
      -var container_image=ghcr.io/web3-storage/aws-ipfs-bitswap-peer/app:${{ github.event.inputs.tag }}
    aws_region: us-west-2
