# This GitHub Actions Workflow will enforce best practices with PRs
# The following tests are performed on each new PR:
#   1. Verify PR title complies with our standard

# For the PR title compliance:
#   Leverages an external GitHub Action: https://github.com/marketplace/actions/pull-request-title-rules
#
#   Functionality:
#   This workflow checks if the PR title matches the following pattern:
#     ^\[(WIP|READY|REVIEW|WAIT)\]\ -\ \[[A-Z]+[0-9]?-\d+\]\ -\ .+
#
#   Meaning PRs must abid by the following syntax:
#     [WIP|READY|REVIEW|WAIT] - [ISSUE-NUMBER] - Some Title
#

name: PR Verifier

on:
  pull_request:
    # Required by GitHub Action; this make sure this workflow is fired off every time the PR is updated
    types: [opened, edited, synchronize, reopened]

jobs:

  pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Get Approval Status
        id: get_approval_state
        run: |
          approval_found=false
          for review in "${{github.event.pull_request.reviews}}"; do
            echo inside loop
            echo "$review"
            echo "$review.id"
            echo "$review.state"
            if [ "$review.state" == "APPROVED" ]; then
              approval_found=true
              break
            fi
          done
          echo "approval_state=$approval_found" >> "$GITHUB_OUTPUT"

      - name: Display Approval Result
        env:
          APPROVAL_STATE: ${{ steps.get_approval_state.outputs.approval_state }}
        run: echo "approval_state=${APPROVAL_STATE}"

      - name: Verify PR Title
        uses: deepakputhraya/action-pr-title@v1.0.1
        with:
          regex: '^\[(WIP|READY|REVIEW|WAIT)\]\ -\ \[[A-Z]+[0-9]?-\d+\]\ -\ .+'
        continue-on-error: false
