# This GitHub Actions Workflow will enforce best practices with PRs
# The following tests are performed on each new PR:
#   1. Verify PR title complies with our standard

# For the PR title compliance:
#   Leverages an external GitHub Action: https://github.com/marketplace/actions/pull-request-title-rules
#
#   Functionality:
#   This workflow checks if the PR title matches the following pattern:
#     ^\[(WIP|READY|REVIEW|WAIT)\]\ -\ \[[A-Z]+[0-9]?-\d+\]\ -\ .+
#
#   Meaning PRs must abid by the following syntax:
#     [WIP|READY|REVIEW|WAIT] - [ISSUE-NUMBER] - Some Title
#

name: PR Verifier

on:
  pull_request:
    # Required by GitHub Action; this make sure this workflow is fired off every time the PR is updated
    types: [opened, edited, synchronize, reopened]

jobs:

  pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Verify PR Title
        uses: deepakputhraya/action-pr-title@v1.0.2
        with:
          regex: '^\[(WIP|READY|REVIEW|WAIT)\]\ -\ \[[A-Z]+[0-9]?-\d+\]\ -\ .+'
        continue-on-error: false
