name: 'Terraform AWS Workflow'

on:
  workflow_call:
    inputs:
      options:
        required: false
        type: string
        default: ""
        description: Extra arguments to be used at terraform commands
      aws_region:
        required: true
        type: string
        description: Used for authentication
      working_directory:
        required: true
        type: string
        description: Name of the folder where to find the terraform code to be executed
      environment:
        required: true
        type: string
        description: If this is dev, staging, production, etc. The name of the environment which the infrastructure will be applied to.
    secrets:
      aws_access_key_id:
        required: true
        description: Used for authentication
      aws_secret_access_key:
        required: true
        description: Used for authentication
jobs:
  # TODO: Add a job for deploying at a staging environment and run automated tests
  terraform:
    runs-on: [self-hosted, linux, X64, aws-management-github-runner]
    name: 'Terraform'
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.aws_access_key_id }}
        aws-secret-access-key: ${{ secrets.aws_secret_access_key }}
        aws-region: ${{ inputs.aws_region }}
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
    - name: Terraform Init
      run: terraform init
    - name: Terraform Plan
      run: terraform plan ${{ inputs.options }} -var region=${{ inputs.aws_region }}
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' 
      run: terraform apply ${{ inputs.options }} -var region=${{ inputs.aws_region }} -auto-approve
