name: 'Terraform AWS Workflow'

on:
  workflow_call:
    inputs:
      options:
        required: false
        type: string
        default: ""
      aws_region:
        required: true
        type: string

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production # TODO: Input
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/peer-subsystem # TODO: Input
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.aws_region }}
    - name: test echo
      run: hi I am working
    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v1
    # - name: Terraform Init
    #   run: terraform init
    # - name: Terraform Plan
    #   run: terraform plan ${{ github.event.inputs.options }}
    # - name: Terraform Apply
    #   if: github.ref == 'refs/heads/main' && github.event_name == 'push' # TODO: Check if that second if will be captured event inside shared workflow
    #   run: terraform apply ${{ github.event.inputs.options }} -auto-approve
