name: 'Terraform AWS Workflow'

on:
  workflow_call:
    inputs:
      options:
        required: false
        type: string
        default: ''
      aws_region:
        required: true
        type: string
      working_directory:
        required: true
        type: string
      environment:
        required: true
        type: string
    secrets:
      aws_iam_role_to_assume:
        required: true
jobs:
  # TODO: Add a job for deploying at a staging environment and run automated tests
  terraform:
    runs-on: [self-hosted, linux, X64, aws-management-github-runner]
    # runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    name: 'Terraform'
    environment: ${{ inputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: sudo apt install awscli -y
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.aws_iam_role_to_assume }}
          aws-region: ${{ inputs.aws_region }}
      - run: echo $AWS_PROFILE
      - run: aws configure list
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        run: terraform init
      - name: Terraform Plan
        run: terraform plan ${{ inputs.options }} -var region=${{ inputs.aws_region }}
      - name: Terraform Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply ${{ inputs.options }} -var region=${{ inputs.aws_region }} -auto-approve
