# TODO: Should this be part of the same workflow?
# Maybe make just high or critical block main workflow
### soft_fail_commenter - set to true to to comment silently without breaking the build
name: tfsec
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@master
    - name: tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        soft_fail: true
