apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitswap-peer
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/web3-storage/AWS-IPFS-bitswap-peer.git # TODO: Rename after repo rebranding
    targetRevision: HEAD
    path: helm
    helm:
      releaseName: ipfs-elastic-provider-bitswap-peer
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      selfHeal: true
      prune: true
